# **Experiment Notebook**

---
## 0. Setup Environment

### 0.a Install Mandatory Packages

> Do not modify this code before running it

In [1]:
# Do not modify this code

import os
import sys
from pathlib import Path

COURSE = "36106"
ASSIGNMENT = "AT1"
DATA = "data"

asgmt_path = f"{COURSE}/assignment/{ASSIGNMENT}"
root_path = "./"

print("###### Install required Python packages ######")
! pip install -r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt

if os.getenv("COLAB_RELEASE_TAG"):

    from google.colab import drive
    from pathlib import Path

    print("\n###### Connect to personal Google Drive ######")
    gdrive_path = "/content/gdrive"
    drive.mount(gdrive_path)
    root_path = f"{gdrive_path}/MyDrive/"

print("\n###### Setting up folders ######")
folder_path = Path(f"{root_path}/{asgmt_path}/") / DATA
folder_path.mkdir(parents=True, exist_ok=True)
print(f"\nYou can now save your data files in: {folder_path}")

if os.getenv("COLAB_RELEASE_TAG"):
    %cd {folder_path}

###### Install required Python packages ######
Requirement already satisfied: pandas==2.2.2 in /usr/local/lib/python3.11/dist-packages (from -r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt (line 1)) (2.2.2)
Requirement already satisfied: scikit-learn==1.6.1 in /usr/local/lib/python3.11/dist-packages (from -r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt (line 2)) (1.6.1)
Requirement already satisfied: altair==5.5.0 in /usr/local/lib/python3.11/dist-packages (from -r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt (line 3)) (5.5.0)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas==2.2.2->-r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt (line 1)) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas==2.2.2->-r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt (line 1)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas==2.2.2->-r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt (line 1)) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas==2.2.2->-r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt (line 1)) (2025.1)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.6.1->-r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt (line 2)) (1.14.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.6.1->-r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt (line 2)) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.6.1->-r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt (line 2)) (3.6.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from altair==5.5.0->-r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt (line 3)) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.11/dist-packages (from altair==5.5.0->-r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt (line 3)) (4.23.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.11/dist-packages (from altair==5.5.0->-r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt (line 3)) (1.31.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from altair==5.5.0->-r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt (line 3)) (24.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from altair==5.5.0->-r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt (line 3)) (4.12.2)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair==5.5.0->-r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt (line 3)) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair==5.5.0->-r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt (line 3)) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair==5.5.0->-r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt (line 3)) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=3.0->altair==5.5.0->-r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt (line 3)) (0.23.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas==2.2.2->-r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt (line 1)) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->altair==5.5.0->-r https://raw.githubusercontent.com/aso-uts/labs_datasets/main/36106-mlaa/requirements.txt (line 3)) (3.0.2)

###### Connect to personal Google Drive ######
Mounted at /content/gdrive

###### Setting up folders ######

You can now save your data files in: /content/gdrive/MyDrive/36106/assignment/AT1/data
/content/gdrive/MyDrive/36106/assignment/AT1/data

### 0.b Disable Warnings Messages

> Do not modify this code before running it

In [2]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

### 0.c Install Additional Packages

> If you are using additional packages, you need to install them here using the command: `! pip install <package_name>`

In [ ]:
# <Student to fill this section>

### 0.d Import Packages

In [3]:
import ipywidgets as widgets
import pandas as pd
import altair as alt
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

---
## A. Project Description

In [6]:
# @title Student Information
wgt_student_name = widgets.Text(
    value=None,
    placeholder='<student to fill this section>',
    description='Student Name:',
    style={'description_width': 'initial'},
    disabled=False
)

wgt_student_id = widgets.Text(
    value=None,
    placeholder='<student to fill this section>',
    description='Student Id:',
    style={'description_width': 'initial'},
    disabled=False
)

widgets.HBox([wgt_student_name, wgt_student_id])

HBox(children=(Text(value='', description='Student Name:', placeholder='<student to fill this section>', style…

In [7]:
# @title Experiment ID

wgt_experiment_id = widgets.BoundedIntText(
    value=1,
    min=0,
    max=3,
    step=1,
    description='Experiment ID:',
    style={'description_width': 'initial'},
    disabled=False
)
wgt_experiment_id

BoundedIntText(value=1, description='Experiment ID:', max=3, style=DescriptionStyle(description_width='initial…

In [4]:
# @title Business Objective

wgt_business_objective = widgets.Textarea(
    value=None,
    placeholder='<student to fill this section>',
    description='Business Objective:',
    disabled=False,
    style={'description_width': 'initial'},
    layout=widgets.Layout(height="100%", width="auto")
)
wgt_business_objective

Textarea(value='', description='Business Objective:', layout=Layout(height='100%', width='auto'), placeholder=…

---
## B. Experiment Description

In [5]:
# @title Experiment Hypothesis

wgt_experiment_hypothesis = widgets.Textarea(
    value=None,
    placeholder='<student to fill this section>',
    description='Experiment Hypothesis:',
    disabled=False,
    style={'description_width': 'initial'},
    layout=widgets.Layout(height="100%", width="auto")
)
wgt_experiment_hypothesis

Textarea(value='', description='Experiment Hypothesis:', layout=Layout(height='100%', width='auto'), placehold…

In [8]:

# @title Experiment Expectations

wgt_experiment_expectations = widgets.Textarea(
    value=None,
    placeholder='<student to fill this section>',
    description='Experiment Expectations:',
    disabled=False,
    style={'description_width': 'initial'},
    layout=widgets.Layout(height="100%", width="auto")
)
wgt_experiment_expectations

Textarea(value='', description='Experiment Expectations:', layout=Layout(height='100%', width='auto'), placeho…

---
## C. Data Understanding

### C.1   Load Datasets

> Do not change this code

In [5]:
# Load training data
X_train = pd.read_csv(folder_path / 'X_train.csv')
y_train = pd.read_csv(folder_path / 'y_train.csv')

In [6]:
# Load validation data
X_val = pd.read_csv(folder_path / 'X_val.csv')
y_val = pd.read_csv(folder_path / 'y_val.csv')

In [7]:
# Load testing data
X_test = pd.read_csv(folder_path / 'X_test.csv')
y_test = pd.read_csv(folder_path / 'y_test.csv')

---
## D. Feature Selection

In [8]:
# feature list is the same as the feature list of experiment 0

features_list = ["advertised_date", "number_of_bedrooms", "rent", "floor_area", "level", "suburb", "furnished", "tenancy_preference", "number_of_bathrooms", "point_of_contact"]

In [9]:
# @title Feature Selection Explanation

wgt_feat_selection_explanation = widgets.Textarea(
    value=None,
    placeholder='<student to fill this section>',
    description='Feature Selection Explanation:',
    disabled=False,
    style={'description_width': 'initial'},
    layout=widgets.Layout(height="100%", width="auto")
)
wgt_feat_selection_explanation

Textarea(value='', description='Feature Selection Explanation:', layout=Layout(height='100%', width='auto'), p…

---
## E. Train Machine Learning Model

### E.1 Import Algorithm

> Provide some explanations on why you believe this algorithm is a good fit

In [9]:
#import linear regression model
from sklearn.linear_model import LinearRegression

In [10]:
# @title Algorithm Selection Explanation

wgt_algo_selection_explanation = widgets.Textarea(
    value=None,
    placeholder='<student to fill this section>',
    description='Algorithm Selection Explanation:',
    disabled=False,
    style={'description_width': 'initial'},
    layout=widgets.Layout(height="100%", width="auto")
)
wgt_algo_selection_explanation

Textarea(value='', description='Algorithm Selection Explanation:', layout=Layout(height='100%', width='auto'),…

### E.2 Set Hyperparameters

> Provide some explanations on why you believe this algorithm is a good fit

In [18]:
model_with_intercept = LinearRegression(fit_intercept = True)
model_wthout_intercept = LinearRegression(fit_intercept = False)

In [19]:
X_train.head()

,number_of_bedrooms,number_of_bathrooms,advertised_month,suburb_Brisbane,suburb_Canberra,suburb_Melbourne,suburb_Perth,suburb_Sydney,furnished_Semi-Furnished,furnished_Unfurnished,tenancy_preference_Bachelors/Family,tenancy_preference_Family,point_of_contact_Contact Owner,level_Low,level_Medium,log_floor_area
0,-0.02794,0.144459,-0.622459,-0.503366,2.614938,-0.475009,-0.457415,-0.463456,-0.927198,1.227872,0.575893,-0.303757,0.586657,0.244735,-0.215238,0.543802
1,-0.02794,-1.047675,-0.622459,-0.503366,2.614938,-0.475009,-0.457415,-0.463456,1.078518,-0.814417,0.575893,-0.303757,0.586657,0.244735,-0.215238,0.095287
2,-0.02794,-1.047675,-0.622459,-0.503366,2.614938,-0.475009,-0.457415,-0.463456,1.078518,-0.814417,0.575893,-0.303757,0.586657,0.244735,-0.215238,0.409566
3,-0.02794,-1.047675,-0.622459,-0.503366,2.614938,-0.475009,-0.457415,-0.463456,-0.927198,1.227872,-1.736434,-0.303757,0.586657,0.244735,-0.215238,0.180672
4,-0.02794,0.144459,-2.271301,-0.503366,2.614938,-0.475009,-0.457415,-0.463456,-0.927198,1.227872,0.575893,-0.303757,0.586657,0.244735,-0.215238,-0.309889

In [20]:
y_train.head()

    rent
0  568.0
1  581.0
2  577.0
3  565.0
4  564.0

In [11]:
# @title Hyperparameters Selection Explanation

wgt_hyperparams_selection_explanation = widgets.Textarea(
    value=None,
    placeholder='<student to fill this section>',
    description='Hyperparameters Selection Explanation:',
    disabled=False,
    style={'description_width': 'initial'},
    layout=widgets.Layout(height="2000%", width="auto")
)
wgt_hyperparams_selection_explanation

Textarea(value='', description='Hyperparameters Selection Explanation:', layout=Layout(height='2000%', width='…

### E.3 Fit Model

In [21]:
# Fit the LinearRegression Model
model_with_intercept.fit(X_train, y_train)
model_wthout_intercept.fit(X_train, y_train)

LinearRegression(fit_intercept=False)

In [14]:
X_val.head()

,advertised_month,suburb_Brisbane,suburb_Canberra,suburb_Melbourne,suburb_Perth,suburb_Sydney,furnished_Semi-Furnished,furnished_Unfurnished,tenancy_preference_Bachelors/Family,tenancy_preference_Family,point_of_contact_Contact Owner,level_Low,level_Medium,log_num_of_bed,log_num_of_bath,log_floor_area
0,1.026384,-0.503366,-0.382418,2.105223,-0.457415,-0.463456,1.078518,-0.814417,-1.736434,3.292101,0.586657,0.244735,-0.215238,0.174266,0.360523,-0.407060
1,1.026384,-0.503366,-0.382418,-0.475009,-0.457415,2.157703,-0.927198,1.227872,0.575893,-0.303757,-1.704575,0.244735,-0.215238,0.174266,0.360523,0.004390
2,-2.271301,-0.503366,-0.382418,-0.475009,-0.457415,-0.463456,-0.927198,1.227872,0.575893,-0.303757,0.586657,0.244735,-0.215238,1.134887,0.360523,0.337324
3,-0.622459,-0.503366,-0.382418,-0.475009,-0.457415,2.157703,1.078518,-0.814417,-1.736434,-0.303757,0.586657,0.244735,-0.215238,-1.467926,-1.235820,-0.566674
4,-2.271301,1.986627,-0.382418,-0.475009,-0.457415,-0.463456,1.078518,-0.814417,0.575893,-0.303757,0.586657,0.244735,-0.215238,0.174266,0.360523,-0.309889

### E.4 Model Technical Performance

> Provide some explanations on model performance

In [22]:
# Import performance metrix
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import root_mean_squared_error as rmse

#Predict the training data
y_train_pred_T = model_with_intercept.predict(X_train)
y_train_pred_F = model_wthout_intercept.predict(X_train)

#Predict the validation data
y_val_pred_T = model_with_intercept.predict(X_val)
y_val_pred_F = model_wthout_intercept.predict(X_val)

y_test_pred_T = model_with_intercept.predict(X_test)
y_test_pred_F = model_wthout_intercept.predict(X_test)

In [24]:
# Calculate RMSE and MSE for training data
train_rmse_T = rmse(y_train, y_train_pred_T)
train_mse_T = mse(y_train, y_train_pred_T)

# Calculate RMSE and MSE for validation data
val_rmse_T = rmse(y_val, y_val_pred_T)
val_mse_T = mse(y_val, y_val_pred_T)

#Calculate RMSE and MSE for testing data
test_rmse_T = rmse(y_test, y_test_pred_T)
test_mse_T = mse(y_test, y_test_pred_T)

# Print the results
print('Train Root Mean Square Error with Intercept: ', train_rmse_T, '\n')
print('Train Mean Square Error with Intercept: ', train_mse_T, '\n')
print('Validation Root Mean Square Error with Intercept: ', val_rmse_T, '\n')
print('Validation Mean Square Error with Intercept: ', val_mse_T, '\n')
print('Test Root Mean Square Error with Intercept: ', test_rmse_T, '\n')
print('Test Mean Square Error with Intercept: ', test_mse_T, '\n')

Train Root Mean Square Error with Intercept:  92.6351838750427

Train Mean Square Error with Intercept:  8581.277291562972

Validation Root Mean Square Error with Intercept:  47.55337440314931

Validation Mean Square Error with Intercept:  2261.323417126096

Test Root Mean Square Error with Intercept:  54.66357892637961

Test Mean Square Error with Intercept:  2988.1068610405323

In [25]:
# Calculate RMSE and MSE for training data
train_rmse_F = rmse(y_train, y_train_pred_F)

# Calculate RMSE and MSE for validation data
val_rmse_F = rmse(y_val, y_val_pred_F)

#Calculate RMSE and MSE for testing data
test_rmse_F = rmse(y_test, y_test_pred_F)

# Print the results
print('Train Root Mean Square Error without Intercept: ', train_rmse_F, '\n')
print('Validation Root Mean Square Error without Intercept: ', val_rmse_F, '\n')
print('Test Root Mean Square Error without Intercept: ', test_rmse_F, '\n')

Train Root Mean Square Error without Intercept:  602.185538167953

Validation Root Mean Square Error without Intercept:  592.6682914537456

Test Root Mean Square Error without Intercept:  592.9296965590084

In [38]:
perfect = alt.Chart(pd.DataFrame({'target': y_train.values.flatten(), 'preds': y_train.values.flatten()})).mark_line(color='green').encode(
    x='target',
    y='preds'
)

pred_chart_train = alt.Chart(pd.DataFrame({'target': y_train.values.flatten(), 'preds': y_train_pred_T.flatten()})).mark_line().encode(
    x='target',
    y='preds'
)

(pred_chart_train + perfect).properties(title = 'Predictions vs Actuals for Traning Data with Intercep')

alt.LayerChart(...)

In [34]:
perfect = alt.Chart(pd.DataFrame({'target': y_train.values.flatten(), 'preds': y_train.values.flatten()})).mark_line(color='green').encode(
    x='target',
    y='preds'
)

# Removed .values and used .flatten() directly on the NumPy arrays
pred_chart_train = alt.Chart(pd.DataFrame({'target': y_train.values.flatten(), 'preds': y_train_pred_F.flatten()})).mark_line().encode(
    x='target',
    y='preds'
)

(pred_chart_train + perfect).properties(title = 'Predictions vs Actuals for Traning Data without Intercep')

alt.LayerChart(...)

In [40]:
perfect = alt.Chart(pd.DataFrame({'target': y_val.values.flatten(), 'preds': y_val.values.flatten()})).mark_line(color='green').encode(
    x='target',
    y='preds'
)

pred_chart_val = alt.Chart(pd.DataFrame({'target': y_val.values.flatten(), 'preds': y_val_pred_T.flatten()})).mark_line().encode(
    x='target',
    y='preds'
)

(pred_chart_val + perfect).properties(title = 'Predictions vs Actuals for Validation Data with Intercep')

alt.LayerChart(...)

In [36]:
perfect = alt.Chart(pd.DataFrame({'target': y_val.values.flatten(), 'preds': y_val.values.flatten()})).mark_line(color='green').encode(
    x='target',
    y='preds'
)

pred_chart_val = alt.Chart(pd.DataFrame({'target': y_val.values.flatten(), 'preds': y_val_pred_F.flatten()})).mark_line().encode(
    x='target',
    y='preds'
)

(pred_chart_val + perfect).properties(title = 'Predictions vs Actuals for Validation Data without Intercep')

alt.LayerChart(...)

In [32]:
perfect = alt.Chart(pd.DataFrame({'target': y_test.values.flatten(), 'preds': y_test.values.flatten()})).mark_line(color='green').encode(
    x='target',
    y='preds'
)

pred_chart_test = alt.Chart(pd.DataFrame({'target': y_test.values.flatten(), 'preds': y_test_pred_T.flatten()})).mark_line().encode(
    x='target',
    y='preds'
)

(pred_chart_test + perfect).properties(title = 'Predictions vs Actuals for Testing Data with Intercep')

alt.LayerChart(...)

In [41]:
perfect = alt.Chart(pd.DataFrame({'target': y_test.values.flatten(), 'preds': y_test.values.flatten()})).mark_line(color='green').encode(
    x='target',
    y='preds'
)

pred_chart_test = alt.Chart(pd.DataFrame({'target': y_test.values.flatten(), 'preds': y_test_pred_F.flatten()})).mark_line().encode(
    x='target',
    y='preds'
)

(pred_chart_test + perfect).properties(title = 'Predictions vs Actuals for Testing Data without Intercep')

alt.LayerChart(...)

In [29]:
# @title Model Performance Explanation

wgt_model_performance_explanation = widgets.Textarea(
    value=None,
    placeholder='<student to fill this section>',
    description='Model Performance Explanation:',
    disabled=False,
    style={'description_width': 'initial'},
    layout=widgets.Layout(height="100%", width="auto")
)
wgt_model_performance_explanation

Textarea(value='', description='Model Performance Explanation:', layout=Layout(height='100%', width='auto'), p…

### E.5 Business Impact from Current Model Performance

> Provide some analysis on the model impacts from the business point of view

In [42]:
import math

# Select numeric and boolean features
X_train_numeric = X_train.select_dtypes(include=['number', 'bool'])
X_val_numeric = X_val.select_dtypes(include=['number', 'bool'])
X_test_numeric = X_test.select_dtypes(include=['number', 'bool'])

# Convert boolean features to 1s and 0s
X_train_numeric = X_train_numeric.astype(float)
X_val_numeric = X_val_numeric.astype(float)
X_test_numeric = X_test_numeric.astype(float)

reg = LinearRegression()

# Assuming 'reg' is your trained LinearRegression model
# Re-fit the model using only numeric features
reg.fit(X_train_numeric, y_train)

# Print the model coefficients
print("Intercept:", model_with_intercept.intercept_)
print("Coefficients:")
for feature, coef in zip(X_train_numeric.columns, reg.coef_[0]):
    print(f"  {feature}: {coef}")

# We use the score method to get r-squared
print('\nR-squared:', reg.score(X_train_numeric, y_train))

# We can also calculate the standard error
stderr = math.sqrt(np.mean((y_train.values.ravel() - reg.predict(X_train_numeric).ravel())**2))

Intercept: [595.01776872]
Coefficients:
  number_of_bedrooms: 9.147026420252248
  number_of_bathrooms: 22.121480656239207
  advertised_month: 1.3568782400617407
  suburb_Brisbane: -0.8825725843170305
  suburb_Canberra: -2.384870713120593
  suburb_Melbourne: -5.318121067015982
  suburb_Perth: -7.4727556540334525
  suburb_Sydney: 16.16663568557749
  furnished_Semi-Furnished: -3.5358851426513085
  furnished_Unfurnished: -4.758419408222189
  tenancy_preference_Bachelors/Family: -0.4947431816452825
  tenancy_preference_Family: -4.337574054036224
  point_of_contact_Contact Owner: -10.572450715070175
  level_Low: -13.447156066369867
  level_Medium: -11.575011985955111
  log_floor_area: 6.924768655290982

R-squared: 0.22632157863720115

In [43]:
# @title Model Business Impacts Explanation

wgt_model_business_explanation = widgets.Textarea(
    value=None,
    placeholder='<student to fill this section>',
    description='Model Business Impacts Explanation:',
    disabled=False,
    style={'description_width': 'initial'},
    layout=widgets.Layout(height="100%", width="auto")
)
wgt_model_business_explanation

Textarea(value='', description='Model Business Impacts Explanation:', layout=Layout(height='100%', width='auto…

## F. Experiment Outcomes

In [6]:
# @title Experiment Outcomes Explanation

wgt_experiment_outcomes_explanation = widgets.Select(
    options=['Hypothesis Confirmed', 'Hypothesis Partially Confirmed', 'Hypothesis Rejected'],
    value='Hypothesis Rejected',
    description='Experiment Outcomes:',
    disabled=False,
)

wgt_experiment_outcomes_explanation

Select(description='Experiment Outcomes:', index=2, options=('Hypothesis Confirmed', 'Hypothesis Partially Con…

In [7]:
# @title Experiments Results Explanation

wgt_experiment_results_explanation = widgets.Textarea(
    value=None,
    placeholder='<student to fill this section>',
    description='Experiments Results Explanation:',
    disabled=False,
    style={'description_width': 'initial'},
    layout=widgets.Layout(height="100%", width="auto")
)
wgt_experiment_results_explanation

Textarea(value='', description='Experiments Results Explanation:', layout=Layout(height='100%', width='auto'),…